spring.application.name=sistema de manejo de alumnos
server.port=8081

# H2 DB en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 consola web habilitada
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Usar esquema generado por Spring JPA (opcional)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
